### PR TITLE
S4 changes for correct operations on 'nanotime' operands

### PR DESCRIPTION
**Pull request by lsilvest**

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Please make this change:

```
1 file changed, 1 insertion(+), 1 deletion(-)
.travis.yml | 2 +-

modified   .travis.yml
@@ -13,7 +13,7 @@ before_install:
   - ./run.sh bootstrap
 
 install:
-  - ./run.sh install_aptget r-cran-rcppcctz r-cran-bit64 r-cran-zoo r-cran-data.table
+  - ./run.sh install_aptget r-cran-rcppcctz r-cran-bit64 r-cran-zoo r-cran-data.table r-cran-runit
 
 script:
   - ./run.sh run_tests
```

**Comment by eddelbuettel** [comment]
Forgot that GH is so fancy now and lets _me_ commit directly into your `master` to alter the pending PR.

So I pushed the change, and Travis should now be happier.

**Comment by eddelbuettel** [comment]
Well turns out it is not -- while it now runs tests thanks to RUnit being installed, it still fails.  So that is now a PR with busted tests so ball back in your court.

**Comment by lsilvest** [comment]
Yes, it failed a test that works fine on my machine. I've created a Travis account and will look into this failure.

**Comment by eddelbuettel** [comment]
It also passes for me on my box (as I mentioned on Slack, not sure if you're logged in).

Older compiler?  Older OS version?

**Pull request merged**
