### PR TITLE
feat: '+' / '-' methods for {nanotime} objects and 'difftime()' objects

### LINKED ISSUE #107: Add/subtract methods for nanoduration/difftime durations
* As a follow-up to #106 I could do a PR to add S4 "+"/"-" methods to add difftime and nanoduration durations together

### LINKED ISSUE #108: Add/subtract methods for nanotime datetimes and difftime durations
* As a follow-up to #106 I could do a PR to add S4 "+"/"-" methods to add difftime durations and nanotime datetimes together

### PR DESCRIPTION
**Pull request by trevorld**
Adds the following S4 methods:

    * nanoduration() + difftime()
    * difftime() + nanoduration()
    * nanoduration() - difftime()
    * difftime - nanoduration()
    * nanotime() + difftime()
    * difftime() + nanotime()
    * nanotime() - difftime()
    * nanoduration() + nanotime() (arguably missing S4 method)

closes #107, closes #108

### CODE REVIEW

**Review by eddelbuettel — APPROVED** [review]
Thank you -- that too looks good.  I will wait for @lsilvest to nod as well before merging.

**Comment by lsilvest** [comment]
If we do have `difftime` for `nanotime` and `nanoduration`, I think for coherence we also want to do it for `nanoival`, so for that type too we can add/subtract directly a `difftime`.

Also I would ideally prefer the unit tests to be distinct for each function added. Admittedly they are not very complicated, but one never knows what can break down the line and hence if one will need these separate unit tests.

**Comment by trevorld** [comment]
@lsilvest Each new method now has its own individual test and I've added the following new S4 `nanoival()` methods:

    * nanoival() + difftime()
    * difftime() + nanoival()
    * nanoival() - difftime()
    * nanoduration() + nanoival() (arguably missing S4 method)
    * nanoival() - nanoduration() (arguably missing S4 method)

**Review by lsilvest — APPROVED** [review]

**Comment by eddelbuettel** [comment]
Thank you @trevorld for the added (and updated) PR and to @lsilvest for catching that `nanoival` was needed too.

If this completes the set of changes @trevorld is planning to bring I can look into a quick release in a few days.  (Got a few email from CRAN about clang-15 changes I should chew on first so likely early next week for this if we are good with that.)

**Comment by trevorld** [comment]
This completes the set of changes I was planning.

**Comment by eddelbuettel** [comment]
> I can look into a quick release in a few days

Got around to that late yesterday, and by now Uwe processed and the new version is on CRAN.

Many thanks again to @trevorld for all the careful patches in it.

**Pull request merged**
